# -*- coding: utf-8 -*-
"""keystrength.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ODbYRmxb7Cl-Gto_ggwFaNdzrEqBGPS-
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder

data = pd.read_csv('dataset.csv')

X = data[["strength","length", "entropy"]]
y = data["class_strength"]

label = LabelEncoder()
y_encoded = label.fit_transform(y)


X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)


model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)




input = [0.95,30, 192.77 ]


predicted_strength = model.predict([input])
predicted_outcome = label.inverse_transform(predicted_strength)
print(f"Predicted Key Strength: {predicted_outcome[0]}")